In [47]:
#Date Cleaning. #Wants non values filled in with some sort of median value. Also remove any duplicate job entries

import pandas as pd                        #Dataset
from datasets import load_dataset
import matplotlib.pyplot as plt  

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [ ]:
#Fill in values, replacing null

median_salary_year = df['salary_year_avg'].median()
median_salary_hour = df['salary_hour_avg'].median()

df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)   #fillna
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)
df_filled.loc[:10,'salary_hour_avg':'salary_year_avg']


df_unique = df_filled                              

df_unique = df_unique.drop_duplicates(subset = ['job_title','company_name']) #filter based on job title and company name (unique)
len(df_filled)-len(df_unique)

277699

In [34]:
#Practice Problems

df_cleaned = df.dropna(subset = ['salary_year_avg'])
len(df_cleaned)

df_cleaned = df.drop_duplicates(subset = ['job_location'])
len(df_cleaned)

df_filled = df['salary_rate']= df['salary_rate'].fillna('Unknown')
df_filled.head(10)

0    Unknown
1    Unknown
2    Unknown
3    Unknown
4    Unknown
5    Unknown
6    Unknown
7    Unknown
8    Unknown
9    Unknown
Name: salary_rate, dtype: str

In [ ]:
# Data Management

#Making a sample. A random sample of items from an axis of object

df.sample(10)                       #Random sample of 10 records or jobs
df.sample(10, random_state = 42)    #Output the same result every single time


df_original = dataset['train'].to_pandas()
df_altered = df_original                       #Original dataframe can get updated, which is not a good thing. 
id(df_original)
id(df_altered)             #These variables are referencing the same dataframe

#lets apply the copy method. It makes a copy of an object's indices
df_altered = df_original.copy()                  #Now the variables are referencing different IDs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [58]:
# Practice Problems

df_copy = df.copy()
df_cleaned = df_copy.dropna(subset=['salary_year_avg'])
df_cleaned.head(5)

df_sampled = df.sample(frac=0.1)          #Sample of 10% of original dataframe
df_sampled.head(5)

df_copy = df.copy()
df_copy['salary_year_avg'] = df_copy['salary_year_avg'].fillna(median_salary_year)
df_copy.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

ValueError: Only integers accepted as `n` values